/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package graphiquepackage;

import com.mycompany.miniprojetjava.Jointure;
import com.mycompany.miniprojetjava.Miniprojetjava;
import java.awt.Color;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author semje
 */
public class ApercuVente extends javax.swing.JPanel {

    /**
     * Creates new form ApercuVente
     */
    public ApercuVente() {
        initComponents();
        
        message.setForeground( new Color(0,102,0));
        message.setText("Vous pouvez cliquez sur les entetes des colonnes, pour trier la table suivant cette colonne");
        
        DefaultTableModel model = (DefaultTableModel) jT_apercu.getModel();
        
        Miniprojetjava.baseDeDonnees.getListeJointure();
        
        
        for(Jointure j : Miniprojetjava.baseDeDonnees.liste_Jointures_BD ){
            
            model.addRow(new Object[]{j.cl.idclient, j.cl.nom, j.cl.prenom, j.pd.idproduit, j.pd.nom, j.pd.paysorigine, j.pd.prix, j.vt.quatite});
    
        }
        
        jT_apercu.setAutoCreateRowSorter(true);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        message = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_apercu = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1010, 650));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apercu des ventes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(153, 153, 153))); // NOI18N

        message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        message.setText("message");

        jT_apercu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Client", "Nom Client", "Prenom Client", "Id Produit", "Nom Produit", "Pays Origine Produit", "Prix produit", "Quantite achetee par le client"
            }
        ));
        jT_apercu.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jT_apercu);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Imprimer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(337, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(message)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String titre = "Apercu des ventes";
        
        MessageFormat entete = new MessageFormat(titre);
        
        try {
            jT_apercu.print(JTable.PrintMode.FIT_WIDTH, entete, null);
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, "Erreur : \n" + e, "Impression", JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(null, "Bonjour, bienvenue sur mon application.", "Message d'information", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jT_apercu;
    private javax.swing.JLabel message;
    // End of variables declaration//GEN-END:variables
}
