/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package graphiquepackage;

import com.mycompany.miniprojetjava.Miniprojetjava;
import com.mycompany.miniprojetjava.Personnel;
import com.mycompany.miniprojetjava.Produit;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author semje
 */
public class GestionProduit extends javax.swing.JPanel {

    /**
     * Creates new form GestionProduit
     */
    
    boolean desactivationbouton = false ;
     
    public GestionProduit() {
        initComponents();
        jT_idproduit.setVisible(false);
       
        boutonRestaurer.setVisible(false);
        
        message.setForeground( new Color(0,102,0));
        message.setText("Vous pouvez cliquez sur les entetes des colonnes, pour trier la table suivant cette colonne");
        
        
        
        DefaultTableModel model = (DefaultTableModel) jT_produit.getModel();
        
        String[][] tabprod = Miniprojetjava.baseDeDonnees.getproduitNonSupprimes();
        
        for(int i=0 ; i < tabprod.length ; i++ ){
            model.addRow(tabprod[i]);
        }
        
        jT_produit.setAutoCreateRowSorter(true);
    }
    
    public static void rechercheAutomatique(JTable jt, JTextField jtf, JLabel jl){
        DefaultTableModel dtm = (DefaultTableModel) jt.getModel();
        String mot = jtf.getText().trim();
        
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(dtm);
        jt.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(mot));
        
        int nbre = jt.getRowCount();
        
        if(nbre == 0){
            jl.setForeground(Color.red);
            jl.setText("Aucun item corrspond à ce nom");
        }
        
        if(nbre > 0){
            jl.setForeground( new Color(0,102,0));
            jl.setText("Resultats correspondants : " + nbre);
        }
        
        if(mot.equals("")){
            jl.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_produit = new javax.swing.JTable();
        jT_nom = new javax.swing.JTextField();
        jT_description = new javax.swing.JTextField();
        jT_prix = new javax.swing.JTextField();
        jT_paysorigine = new javax.swing.JTextField();
        jT_tva = new javax.swing.JTextField();
        jT_fournisseur = new javax.swing.JTextField();
        jT_poids = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ajouter = new javax.swing.JButton();
        miseajour = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        voirproduitsupprimes = new javax.swing.JButton();
        boutonRestaurer = new javax.swing.JButton();
        jT_idproduit = new javax.swing.JTextField();
        jT_quantitestock = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jT_Recherche = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        message = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestion des produits", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1010, 650));

        jT_produit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id produit", "Nom", "Description", "Prix", "Pays origine", "Tva", "Fournisseur", "Poids", "Qutite stock"
            }
        ));
        jT_produit.setGridColor(new java.awt.Color(255, 255, 255));
        jT_produit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jT_produitMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jT_produit);

        jT_paysorigine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_paysorigineActionPerformed(evt);
            }
        });

        jT_fournisseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_fournisseurActionPerformed(evt);
            }
        });

        jT_poids.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_poidsActionPerformed(evt);
            }
        });

        jLabel1.setText("Nom :");

        jLabel2.setText("Description :");

        jLabel3.setText("Prix :");

        jLabel4.setText("Pays d'origine : ");

        jLabel5.setText("Tva :");

        jLabel6.setText("Fournisseur :");

        jLabel7.setText("Poids :");

        ajouter.setBackground(new java.awt.Color(0, 204, 204));
        ajouter.setText("Ajouter");
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });

        miseajour.setBackground(new java.awt.Color(0, 204, 204));
        miseajour.setText("Mettre à jour");
        miseajour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miseajourActionPerformed(evt);
            }
        });

        supprimer.setBackground(new java.awt.Color(0, 204, 204));
        supprimer.setText("Supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        voirproduitsupprimes.setBackground(new java.awt.Color(255, 153, 153));
        voirproduitsupprimes.setText("Voir les produits supprimés");
        voirproduitsupprimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voirproduitsupprimesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(voirproduitsupprimes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(miseajour, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(supprimer, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajouter)
                    .addComponent(miseajour)
                    .addComponent(supprimer))
                .addGap(18, 18, 18)
                .addComponent(voirproduitsupprimes)
                .addGap(17, 17, 17))
        );

        boutonRestaurer.setBackground(new java.awt.Color(153, 204, 255));
        boutonRestaurer.setText("Restaurer le produit");
        boutonRestaurer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonRestaurerActionPerformed(evt);
            }
        });

        jT_idproduit.setText("0");

        jLabel8.setText("Quant. en Stock : ");

        jT_Recherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jT_RechercheKeyReleased(evt);
            }
        });

        jLabel9.setText("Rechercher produit : ");

        message.setForeground(new java.awt.Color(0, 204, 204));
        message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        message.setText("Mesage");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jT_idproduit, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                            .addComponent(jT_fournisseur)
                            .addComponent(jT_tva)
                            .addComponent(jT_paysorigine)
                            .addComponent(jT_prix)
                            .addComponent(jT_description)
                            .addComponent(jT_nom)
                            .addComponent(jT_poids, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                            .addComponent(jT_quantitestock))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jT_Recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boutonRestaurer, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jT_idproduit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(message))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jT_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jT_Recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boutonRestaurer))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jT_description, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jT_prix, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jT_paysorigine, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jT_tva, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jT_fournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jT_poids, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jT_quantitestock, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        
        int id_produit = Integer.parseInt(jT_idproduit.getText());
        
        System.out.println(id_produit);
        
        DefaultTableModel model = (DefaultTableModel) jT_produit.getModel();
        
        if(jT_produit.getSelectedRow() == -1){
            if(jT_produit.getRowCount() == 0){
                message.setText("La facture est encore vide !");
            }
            else{
                message.setText("Vous devriez d'abord selectionner un article de la facture");
            }
        }
        
        else{
            
            int j = jT_produit.getSelectedRow(); 
            int i = jT_produit.convertRowIndexToModel(j);
            
            
            Miniprojetjava.baseDeDonnees.supprimerProduit_BD(id_produit);
            model.removeRow(i);
                    
            jT_idproduit.setText("0");
            jT_nom.setText("");
            jT_description.setText("");
            jT_prix.setText("0");
            jT_paysorigine.setText("");
            jT_tva.setText("0");
            jT_fournisseur.setText("");
            jT_poids.setText("0");
            jT_quantitestock.setText("0");

            message.setText("Cliquez sur le bouton ajouter pour ajouter un produit à la facture");
            
        }
        
    }//GEN-LAST:event_supprimerActionPerformed

    private void boutonRestaurerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonRestaurerActionPerformed
        
        int id_produit = Integer.parseInt(jT_idproduit.getText());
        
        System.out.println(id_produit);
        
        DefaultTableModel model = (DefaultTableModel) jT_produit.getModel();
        
        if(jT_produit.getSelectedRow() == -1){
            if(jT_produit.getRowCount() == 0){
                message.setText("La facture est encore vide !");
            }
            else{
                message.setText("Vous devriez d'abord selectionner un article de la facture");
            }
        }
        
        else{
            
            int j = jT_produit.getSelectedRow(); 
            int i = jT_produit.convertRowIndexToModel(j);
            
            
            Miniprojetjava.baseDeDonnees.restaurerProduitSupprime(id_produit);
            model.removeRow(i);
                    
            jT_idproduit.setText("0");
            jT_nom.setText("");
            jT_description.setText("");
            jT_prix.setText("0");
            jT_paysorigine.setText("");
            jT_tva.setText("0");
            jT_fournisseur.setText("");
            jT_poids.setText("0");
            jT_quantitestock.setText("0");

            message.setText("Cliquez sur le bouton ajouter pour ajouter un produit à la facture");
            
        }
        
    }//GEN-LAST:event_boutonRestaurerActionPerformed

    private void jT_paysorigineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_paysorigineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_paysorigineActionPerformed

    private void jT_fournisseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_fournisseurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_fournisseurActionPerformed

    private void jT_poidsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_poidsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_poidsActionPerformed

    private void jT_RechercheKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_RechercheKeyReleased
        
        JPanel_Caissier.rechercheAutomatique(jT_produit, jT_Recherche, message);
        
        if(message.getText().equals("")){
            message.setText("Vous pouvez cliquez sur les entetes des colonnes, pour trier la table suivant cette colonne");
        }
    }//GEN-LAST:event_jT_RechercheKeyReleased

    private void voirproduitsupprimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voirproduitsupprimesActionPerformed

        if( ! desactivationbouton){
            
            String[][] tabprodSup = Miniprojetjava.baseDeDonnees.getproduitSupprimes();
                
            DefaultTableModel model = (DefaultTableModel) jT_produit.getModel();

            model.setRowCount(0);

            String[] columnNames = {"Id produit", "Nom", "Description", "Prix", "Pays origine", "Tva", "Fournisseur", "Poids", "Qutite stock"};

            model.setDataVector(tabprodSup, columnNames );

            boutonRestaurer.setVisible(true);

            voirproduitsupprimes.setText("Revenir en arrière");

            ajouter.setEnabled(desactivationbouton);
            miseajour.setEnabled(desactivationbouton);
            supprimer.setEnabled(desactivationbouton);
            
            desactivationbouton = true ;
        }
        else{
            
            String[][] tabprodSup = Miniprojetjava.baseDeDonnees.getproduitNonSupprimes();
                
            DefaultTableModel model = (DefaultTableModel) jT_produit.getModel();

            model.setRowCount(0);

            String[] columnNames = {"Id produit", "Nom", "Description", "Prix", "Pays origine", "Tva", "Fournisseur", "Poids", "Qutite stock"};

            model.setDataVector(tabprodSup, columnNames );

            boutonRestaurer.setVisible(false);

            voirproduitsupprimes.setText("Voir les produits supprimés");

            ajouter.setEnabled(desactivationbouton);
            miseajour.setEnabled(desactivationbouton);
            supprimer.setEnabled(desactivationbouton);
            
            desactivationbouton = false ;
        }
    }//GEN-LAST:event_voirproduitsupprimesActionPerformed

    private void jT_produitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_produitMouseClicked
        
        try{
            
            int j = jT_produit.getSelectedRow(); 
            int i = jT_produit.convertRowIndexToModel(j);
            
            TableModel tm = jT_produit.getModel();
            
            jT_idproduit.setText(tm.getValueAt(i,0).toString());
            jT_nom.setText(tm.getValueAt(i,1).toString());
            jT_description.setText(tm.getValueAt(i,2).toString());
            jT_prix.setText(tm.getValueAt(i,3).toString());
            jT_paysorigine.setText(tm.getValueAt(i,4).toString());
            jT_tva.setText(tm.getValueAt(i,5).toString());
            jT_fournisseur.setText(tm.getValueAt(i,6).toString());
            jT_poids.setText(tm.getValueAt(i,7).toString());
            jT_quantitestock.setText(tm.getValueAt(i,8).toString());
        }
        catch(Exception e){
            message.setText("Vous devez cliquez sur ligne !");
        }
    }//GEN-LAST:event_jT_produitMouseClicked

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        
        
        int id_produit = 0 ;
        double prix = 0 ;
        double tva = 0 ;
        double poids = 0 ;
        double quantite_stock = 0 ;
        
        if(jT_nom.getText().equals("")  || jT_description.getText().equals("")  || jT_prix.getText().equals("") || jT_paysorigine.getText().equals("") || jT_tva.getText().equals("") || jT_fournisseur.getText().equals("") || jT_poids.getText().equals("") || jT_quantitestock.getText().equals("")){
            message.setText("Tous les champs doivent être remplis");
        }
        else{
            try{
                prix = Double.parseDouble(jT_prix.getText());
                tva = Double.parseDouble(jT_tva.getText());
                poids = Double.parseDouble(jT_poids.getText());
                quantite_stock = Double.parseDouble(jT_quantitestock.getText());
                
                int option = JOptionPane.showOptionDialog(
                    null,                             // Parent component
                    "Voulez-vous vraiment l'ajouter comme un nouveau produit ?",       // Message
                    "Confirmation",                  // Titre de la boîte de dialogue
                    JOptionPane.YES_NO_OPTION,        // Type de boîte de dialogue
                    JOptionPane.QUESTION_MESSAGE,    // Type d'icône
                    null,                             // Options personnalisées
                    null,                             // Option sélectionnée par défaut
                    null                              // Options de fermeture de la boîte de dialogue
                );

                if (option == JOptionPane.YES_OPTION) {
    

                    id_produit = Miniprojetjava.baseDeDonnees.dernier_id_produit + 1 ;
                
                    Produit p = new Produit( id_produit +"_"+ jT_nom.getText() + "_" + jT_description.getText() + "_" + jT_prix.getText() + "_" + jT_paysorigine.getText() + "_" + jT_tva.getText() + "_" + jT_fournisseur.getText() + "_" + jT_poids.getText() + "_" + jT_quantitestock.getText() + "_0");

                    DefaultTableModel model = (DefaultTableModel) jT_produit.getModel();
                    model.addRow(new Object[]{p.idproduit, p.nom, p.description, p.prix , p.paysorigine, p.tva, p.fournisseur, p.poids, p.quatitestock});
                    
                    Miniprojetjava.baseDeDonnees.ajouterProduit_BD(p);

                    jT_idproduit.setText("0");
                    jT_nom.setText("");
                    jT_description.setText("");
                    jT_prix.setText("0");
                    jT_paysorigine.setText("");
                    jT_tva.setText("0");
                    jT_fournisseur.setText("");
                    jT_poids.setText("0");
                    jT_quantitestock.setText("0");


                    message.setText("Vous pouvez cliquez sur les entetes des colonnes, pour trier la table suivant cette colonne");
                }

                else{
                    message.setText("Vous pouvez cliquez sur les entetes des colonnes, pour trier la table suivant cette colonne");
                }

            }

            catch(Exception e){
                message.setText("Le prix, tva, poids, qutite stock doivent être des nombres");
            }
        }
        
        
    }//GEN-LAST:event_ajouterActionPerformed

    private void miseajourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miseajourActionPerformed
        
        int id_produit = 0 ;
        double prix = 0 ;
        double tva = 0 ;
        double poids = 0 ;
        double quantite_stock = 0 ;
        
        if(jT_nom.getText().equals("")  || jT_description.getText().equals("")  || jT_prix.getText().equals("") || jT_paysorigine.getText().equals("") || jT_tva.getText().equals("") || jT_fournisseur.getText().equals("") || jT_poids.getText().equals("") || jT_quantitestock.getText().equals("")){
            message.setText("Tous les champs doivent être remplis");
        }
        else{
            try{
                prix = Double.parseDouble(jT_prix.getText());
                tva = Double.parseDouble(jT_tva.getText());
                poids = Double.parseDouble(jT_poids.getText());
                quantite_stock = Double.parseDouble(jT_quantitestock.getText());
                
                int option = JOptionPane.showOptionDialog(
                    null,                             // Parent component
                    "Voulez-vous vraiment modifier ce produit ?",       // Message
                    "Confirmation",                  // Titre de la boîte de dialogue
                    JOptionPane.YES_NO_OPTION,        // Type de boîte de dialogue
                    JOptionPane.QUESTION_MESSAGE,    // Type d'icône
                    null,                             // Options personnalisées
                    null,                             // Option sélectionnée par défaut
                    null                              // Options de fermeture de la boîte de dialogue
                );

                if (option == JOptionPane.YES_OPTION) {
    

                    id_produit = Integer.parseInt(jT_idproduit.getText());
                
                    Produit p = new Produit( id_produit +"_"+ jT_nom.getText() + "_" + jT_description.getText() + "_" + jT_prix.getText() + "_" + jT_paysorigine.getText() + "_" + jT_tva.getText() + "_" + jT_fournisseur.getText() + "_" + jT_poids.getText() + "_" + jT_quantitestock.getText() + "_0");

                    DefaultTableModel model = (DefaultTableModel) jT_produit.getModel();
                    
                    //model.addRow(new Object[]{p.idproduit, p.nom, p.description, p.prix , p.paysorigine, p.tva, p.fournisseur, p.poids, p.quatitestock});
                    
                    
                    model.setValueAt(p.idproduit, jT_produit.getSelectedRow(), 0);
                    model.setValueAt(p.nom, jT_produit.getSelectedRow(), 1);
                    model.setValueAt(p.description, jT_produit.getSelectedRow(), 2);
                    model.setValueAt(p.prix, jT_produit.getSelectedRow(), 3);
                    model.setValueAt(p.paysorigine, jT_produit.getSelectedRow(), 4);
                    model.setValueAt(p.tva, jT_produit.getSelectedRow(), 5);
                    model.setValueAt(p.fournisseur, jT_produit.getSelectedRow(), 6);
                    model.setValueAt(p.poids, jT_produit.getSelectedRow(), 7);
                    model.setValueAt(p.quatitestock, jT_produit.getSelectedRow(), 7);

                    //model.addRow(new Object[]{p.idpersonnel, p.nom, p.prenom, p.adresse , p.adresselieutravail, p.poste, p.numerobadge, p.idsuperieur});

                    Miniprojetjava.baseDeDonnees.modifierProduit_BD(id_produit, p);
                    
                    
                    jT_idproduit.setText("0");
                    jT_nom.setText("");
                    jT_description.setText("");
                    jT_prix.setText("0");
                    jT_paysorigine.setText("");
                    jT_tva.setText("0");
                    jT_fournisseur.setText("");
                    jT_poids.setText("0");
                    jT_quantitestock.setText("0");


                    message.setText("Vous pouvez cliquez sur les entetes des colonnes, pour trier la table suivant cette colonne");
                }

                else{
                    message.setText("Vous pouvez cliquez sur les entetes des colonnes, pour trier la table suivant cette colonne");
                }

            }

            catch(Exception e){
                message.setText("Le prix, tva, poids, qutite stock doivent être des nombres");
            }
        }
        
    }//GEN-LAST:event_miseajourActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter;
    private javax.swing.JButton boutonRestaurer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jT_Recherche;
    private javax.swing.JTextField jT_description;
    private javax.swing.JTextField jT_fournisseur;
    private javax.swing.JTextField jT_idproduit;
    private javax.swing.JTextField jT_nom;
    private javax.swing.JTextField jT_paysorigine;
    private javax.swing.JTextField jT_poids;
    private javax.swing.JTextField jT_prix;
    private javax.swing.JTable jT_produit;
    private javax.swing.JTextField jT_quantitestock;
    private javax.swing.JTextField jT_tva;
    private javax.swing.JLabel message;
    private javax.swing.JButton miseajour;
    private javax.swing.JButton supprimer;
    private javax.swing.JButton voirproduitsupprimes;
    // End of variables declaration//GEN-END:variables
}
