/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package graphiquepackage;

import com.mycompany.miniprojetjava.Client;
import com.mycompany.miniprojetjava.Miniprojetjava;
import com.mycompany.miniprojetjava.Produit;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author semje
 */
public class GestionClient extends javax.swing.JPanel {

    /**
     * Creates new form GestionClient
     */
    
    boolean desactivationbouton = false ;
    
    public GestionClient() {
        initComponents();
        
        jT_idclient.setVisible(false);
       
       
        boutonRestaurer.setVisible(false);
        
        message.setForeground( new Color(0,102,0));
        message.setText("Vous pouvez cliquez sur les entetes des colonnes, pour trier la table suivant cette colonne");
        
        
        
        DefaultTableModel model = (DefaultTableModel) jT_clients.getModel();
        
        String[][] tabclients = Miniprojetjava.baseDeDonnees.getClientNonSupprimes();
        
        for(int i=0 ; i < tabclients.length ; i++ ){
            model.addRow(tabclients[i]);
        }
        
        jT_clients.setAutoCreateRowSorter(true);
    }
    
    public static void rechercheAutomatique(JTable jt, JTextField jtf, JLabel jl){
        DefaultTableModel dtm = (DefaultTableModel) jt.getModel();
        String mot = jtf.getText().trim();
        
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(dtm);
        jt.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(mot));
        
        int nbre = jt.getRowCount();
        
        if(nbre == 0){
            jl.setForeground(Color.red);
            jl.setText("Aucun item corrspond à ce nom");
        }
        
        if(nbre > 0){
            jl.setForeground( new Color(0,102,0));
            jl.setText("Resultats correspondants : " + nbre);
        }
        
        if(mot.equals("")){
            jl.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_clients = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ajouter = new javax.swing.JButton();
        miseajour = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        voirclientssupprimes = new javax.swing.JButton();
        boutonRestaurer = new javax.swing.JButton();
        jT_idclient = new javax.swing.JTextField();
        jT_recherche = new javax.swing.JTextField();
        jT_nom = new javax.swing.JTextField();
        jT_prenom = new javax.swing.JTextField();
        jT_numcartefidelite = new javax.swing.JTextField();
        jT_mail = new javax.swing.JTextField();
        jT_codepostale = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        message = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestion des clients", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1010, 650));

        jT_clients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id client", "Nom", "Prenom", "Num carte fidelite", "Mail", "Code postal"
            }
        ));
        jT_clients.setGridColor(new java.awt.Color(255, 255, 255));
        jT_clients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jT_clientsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jT_clients);

        jLabel1.setText("Nom :");

        jLabel2.setText("Prenom : ");

        jLabel3.setText("Num carte fidelite :");

        jLabel4.setText("Mail :");

        jLabel5.setText("Code postal :");

        ajouter.setBackground(new java.awt.Color(0, 204, 204));
        ajouter.setText("Ajouter");
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });

        miseajour.setBackground(new java.awt.Color(0, 204, 204));
        miseajour.setText("Mettre à jour");
        miseajour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miseajourActionPerformed(evt);
            }
        });

        supprimer.setBackground(new java.awt.Color(0, 204, 204));
        supprimer.setText("Supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        voirclientssupprimes.setBackground(new java.awt.Color(255, 153, 153));
        voirclientssupprimes.setText("Voir les clients supprimés");
        voirclientssupprimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voirclientssupprimesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(voirclientssupprimes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(miseajour, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(supprimer, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajouter)
                    .addComponent(miseajour)
                    .addComponent(supprimer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(voirclientssupprimes)
                .addGap(27, 27, 27))
        );

        boutonRestaurer.setBackground(new java.awt.Color(153, 204, 255));
        boutonRestaurer.setText("Restaurer le client");
        boutonRestaurer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonRestaurerActionPerformed(evt);
            }
        });

        jT_idclient.setText("0");

        jT_recherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jT_rechercheKeyReleased(evt);
            }
        });

        jT_numcartefidelite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_numcartefideliteActionPerformed(evt);
            }
        });

        jLabel6.setText("Rechercher Client : ");

        message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        message.setText("message");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boutonRestaurer, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(message, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jT_idclient, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jT_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jT_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jT_numcartefidelite, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jT_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jT_codepostale, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jT_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(message)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jT_idclient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jT_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(jT_nom))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jT_prenom)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(jT_numcartefidelite))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jT_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jT_codepostale, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boutonRestaurer)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        
        int id_client = Integer.parseInt(jT_idclient.getText());
        
        System.out.println(id_client);
        
        DefaultTableModel model = (DefaultTableModel) jT_clients.getModel();
        
        if(jT_clients.getSelectedRow() == -1){
            if(jT_clients.getRowCount() == 0){
                message.setText("La table est encore vide !");
            }
            else{
                message.setText("Vous devriez d'abord selectionner un item de la table");
            }
        }
        
        else{
            
            int j = jT_clients.getSelectedRow(); 
            int i = jT_clients.convertRowIndexToModel(j);
            
            
            Miniprojetjava.baseDeDonnees.supprimerClient_BD(id_client);
            model.removeRow(i);
                    
            jT_idclient.setText("0");
            jT_nom.setText("");
            jT_prenom.setText("");
            jT_numcartefidelite.setText("");
            jT_mail.setText("");
            jT_codepostale.setText("");

            message.setText("Cliquez sur le bouton ajouter pour ajouter un client à la table");
            
        }
    }//GEN-LAST:event_supprimerActionPerformed

    private void boutonRestaurerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonRestaurerActionPerformed

        int id_client = Integer.parseInt(jT_idclient.getText());
        
        System.out.println(id_client);
        
        DefaultTableModel model = (DefaultTableModel) jT_clients.getModel();
        
        if(jT_clients.getSelectedRow() == -1){
            if(jT_clients.getRowCount() == 0){
                message.setText("La table est encore vide !");
            }
            else{
                message.setText("Vous devriez d'abord selectionner un item de la table");
            }
        }
        
        else{
            
            int j = jT_clients.getSelectedRow(); 
            int i = jT_clients.convertRowIndexToModel(j);
            
            
            Miniprojetjava.baseDeDonnees.restaurerClientSupprime(id_client);
            model.removeRow(i);
                    
            jT_idclient.setText("0");
            jT_nom.setText("");
            jT_prenom.setText("");
            jT_numcartefidelite.setText("");
            jT_mail.setText("");
            jT_codepostale.setText("");

            message.setText("Cliquez sur le bouton ajouter pour ajouter un client à la table");
            
        }
    }//GEN-LAST:event_boutonRestaurerActionPerformed

    private void jT_numcartefideliteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_numcartefideliteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_numcartefideliteActionPerformed

    private void jT_clientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_clientsMouseClicked
        try{
            
            int j = jT_clients.getSelectedRow(); 
            int i = jT_clients.convertRowIndexToModel(j);
            
            TableModel tm = jT_clients.getModel();
            
            jT_idclient.setText(tm.getValueAt(i,0).toString());
            jT_nom.setText(tm.getValueAt(i,1).toString());
            jT_prenom.setText(tm.getValueAt(i,2).toString());
            jT_numcartefidelite.setText(tm.getValueAt(i,3).toString());
            jT_mail.setText(tm.getValueAt(i,4).toString());
            jT_codepostale.setText(tm.getValueAt(i,5).toString());
            
        }
        catch(Exception e){
            message.setText("Vous devez cliquez sur ligne !");
        }
    }//GEN-LAST:event_jT_clientsMouseClicked

    private void jT_rechercheKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_rechercheKeyReleased
        
        JPanel_Caissier.rechercheAutomatique(jT_clients, jT_recherche, message);
        
        if(message.getText().equals("")){
            message.setText("Vous pouvez cliquez sur les entetes des colonnes, pour trier la table suivant cette colonne");
        }
    }//GEN-LAST:event_jT_rechercheKeyReleased

    private void voirclientssupprimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voirclientssupprimesActionPerformed
        
        
        if( ! desactivationbouton){
            
            String[][] tabprodSup = Miniprojetjava.baseDeDonnees.getClientSupprimes();
                
            DefaultTableModel model = (DefaultTableModel) jT_clients.getModel();

            model.setRowCount(0);

            String[] columnNames = {"Id client", "Nom", "Prenom", "Num carte fidelite", "Mail", "Code postal"};

            model.setDataVector(tabprodSup, columnNames );

            boutonRestaurer.setVisible(true);

            voirclientssupprimes.setText("Revenir en arrière");

            ajouter.setEnabled(desactivationbouton);
            miseajour.setEnabled(desactivationbouton);
            supprimer.setEnabled(desactivationbouton);
            
            desactivationbouton = true ;
        }
        else{
            
            String[][] tabprodSup = Miniprojetjava.baseDeDonnees.getClientNonSupprimes();
                
            DefaultTableModel model = (DefaultTableModel) jT_clients.getModel();

            model.setRowCount(0);

            String[] columnNames = {"Id client", "Nom", "Prenom", "Num carte fidelite", "Mail", "Code postal"};

            model.setDataVector(tabprodSup, columnNames );

            boutonRestaurer.setVisible(false);

            voirclientssupprimes.setText("Voir les clients supprimés");

            ajouter.setEnabled(desactivationbouton);
            miseajour.setEnabled(desactivationbouton);
            supprimer.setEnabled(desactivationbouton);
            
            desactivationbouton = false ;
        }
        
    }//GEN-LAST:event_voirclientssupprimesActionPerformed

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        
        int id_client = 0 ;
        
        if(jT_nom.getText().equals("")  || jT_prenom.getText().equals("")  || jT_numcartefidelite.getText().equals("") || jT_mail.getText().equals("") || jT_codepostale.getText().equals("")){
            message.setText("Tous les champs doivent être remplis");
        }
        else{
            try{
                
                id_client = Integer.parseInt(jT_idclient.getText());
                
                int option = JOptionPane.showOptionDialog(
                    null,                             // Parent component
                    "Voulez-vous vraiment l'ajouter comme un nouveau client ?",       // Message
                    "Confirmation",                  // Titre de la boîte de dialogue
                    JOptionPane.YES_NO_OPTION,        // Type de boîte de dialogue
                    JOptionPane.QUESTION_MESSAGE,    // Type d'icône
                    null,                             // Options personnalisées
                    null,                             // Option sélectionnée par défaut
                    null                              // Options de fermeture de la boîte de dialogue
                );

                if (option == JOptionPane.YES_OPTION) {
    

                    id_client = Miniprojetjava.baseDeDonnees.dernier_id_personne + 1 ;
                
                    Client p = new Client( id_client +"_"+ jT_numcartefidelite.getText() + "_" + jT_mail.getText() + "_" + jT_codepostale.getText() + "_" + jT_nom.getText() + "_" + jT_prenom.getText() + "_0");

                    DefaultTableModel model = (DefaultTableModel) jT_clients.getModel();
                    
                    model.addRow(new Object[]{p.idclient, p.nom, p.prenom, p.numerocartefidelite , p.mail, p.codepostal});
                    
                    Miniprojetjava.baseDeDonnees.ajouterClient_BD(p);
                    
                    jT_idclient.setText("0");
                    jT_nom.setText("");
                    jT_prenom.setText("");
                    jT_numcartefidelite.setText("");
                    jT_mail.setText("");
                    jT_codepostale.setText("");

                    message.setText("Cliquez sur le bouton ajouter pour ajouter un client à la table");

                   
                }

                else{
                    message.setText("Vous pouvez cliquez sur les entetes des colonnes, pour trier la table suivant cette colonne");
                }

            }

            catch(Exception e){
                message.setText("L'ID doit etre un entier");
            }
        }
    }//GEN-LAST:event_ajouterActionPerformed

    private void miseajourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miseajourActionPerformed
        
        
        int id_client = 0 ;
        
        if(jT_nom.getText().equals("")  || jT_prenom.getText().equals("")  || jT_numcartefidelite.getText().equals("") || jT_mail.getText().equals("") || jT_codepostale.getText().equals("")){
            message.setText("Tous les champs doivent être remplis");
        }
        else{
            try{
                id_client = Integer.parseInt(jT_idclient.getText());
                
                
                
                int option = JOptionPane.showOptionDialog(
                    null,                             // Parent component
                    "Voulez-vous vraiment modifier ce client ?",       // Message
                    "Confirmation",                  // Titre de la boîte de dialogue
                    JOptionPane.YES_NO_OPTION,        // Type de boîte de dialogue
                    JOptionPane.QUESTION_MESSAGE,    // Type d'icône
                    null,                             // Options personnalisées
                    null,                             // Option sélectionnée par défaut
                    null                              // Options de fermeture de la boîte de dialogue
                );

                if (option == JOptionPane.YES_OPTION) {
                    
                
                    Client p = new Client( id_client +"_"+ jT_numcartefidelite.getText() + "_" + jT_mail.getText() + "_" + jT_codepostale.getText() + "_" + jT_nom.getText() + "_" + jT_prenom.getText() + "_0");

                    DefaultTableModel model = (DefaultTableModel) jT_clients.getModel();
                    
                    
                    
                    //model.addRow(new Object[]{p.idproduit, p.nom, p.description, p.prix , p.paysorigine, p.tva, p.fournisseur, p.poids, p.quatitestock});
                    
                    
                    model.setValueAt(p.idclient, jT_clients.getSelectedRow(), 0);
                    model.setValueAt(p.nom, jT_clients.getSelectedRow(), 1);
                    model.setValueAt(p.prenom, jT_clients.getSelectedRow(), 2);
                    model.setValueAt(p.numerocartefidelite, jT_clients.getSelectedRow(), 3);
                    model.setValueAt(p.mail, jT_clients.getSelectedRow(), 4);
                    model.setValueAt(p.codepostal, jT_clients.getSelectedRow(), 5);
                    
                    
                    
                    //model.addRow(new Object[]{p.idclient, p.nom, p.prenom, p.numerocartefidelite , p.mail, p.codepostal});
                    
                    Miniprojetjava.baseDeDonnees.modifierClient_BD(id_client, p);
                    
                    jT_idclient.setText("0");
                    jT_nom.setText("");
                    jT_prenom.setText("");
                    jT_numcartefidelite.setText("");
                    jT_mail.setText("");
                    jT_codepostale.setText("");

                    message.setText("Cliquez sur le bouton ajouter pour ajouter un client à la table");

                   
                }

                else{
                    message.setText("Vous pouvez cliquez sur les entetes des colonnes, pour trier la table suivant cette colonne");
                }

            }

            catch(Exception e){
                message.setText("L'ID doit etre un entier");
            }
        }
    }//GEN-LAST:event_miseajourActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter;
    private javax.swing.JButton boutonRestaurer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jT_clients;
    private javax.swing.JTextField jT_codepostale;
    private javax.swing.JTextField jT_idclient;
    private javax.swing.JTextField jT_mail;
    private javax.swing.JTextField jT_nom;
    private javax.swing.JTextField jT_numcartefidelite;
    private javax.swing.JTextField jT_prenom;
    private javax.swing.JTextField jT_recherche;
    private javax.swing.JLabel message;
    private javax.swing.JButton miseajour;
    private javax.swing.JButton supprimer;
    private javax.swing.JButton voirclientssupprimes;
    // End of variables declaration//GEN-END:variables
}
