/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package graphiquepackage;

import com.mycompany.miniprojetjava.Manager;
import com.mycompany.miniprojetjava.Miniprojetjava;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author semje
 */
public class GestionManager extends javax.swing.JPanel {

    /**
     * Creates new form GestionManager
     */
    
    boolean desactivationbouton = false ;
    
    public GestionManager() {
        initComponents();
        jT_idpersonnel.setVisible(false);
        
        boutonRestaurer.setVisible(false);
        
        message.setForeground( new Color(0,102,0));
        message.setText("Vous pouvez cliquez sur les entetes des colonnes, pour trier la table suivant cette colonne");
        
        
        
        DefaultTableModel model = (DefaultTableModel) jT_personnel.getModel();
        
        String[][] tabper = Miniprojetjava.baseDeDonnees.getmanagerNonSupprimes();
        
        for(int i=0 ; i < tabper.length ; i++ ){
            model.addRow(tabper[i]);
        }
        
        jT_personnel.setAutoCreateRowSorter(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_personnel = new javax.swing.JTable();
        jT_nom = new javax.swing.JTextField();
        jT_prenom = new javax.swing.JTextField();
        jT_adresse = new javax.swing.JTextField();
        jT_adresse_travail = new javax.swing.JTextField();
        jT_poste = new javax.swing.JTextField();
        jT_num_badge = new javax.swing.JTextField();
        jT_idsup = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ajouter = new javax.swing.JButton();
        miseajour = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        voirpersonnelsupprimes = new javax.swing.JButton();
        boutonRestaurer = new javax.swing.JButton();
        jT_idpersonnel = new javax.swing.JTextField();
        message = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jT_codemanager = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestion des personnels", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(1010, 650));

        jT_personnel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id personnel", "Nom", "Prenom", "Adresse", "Adresse lieu travail", "Poste", "Num badge", "Id superieur", "Code manager"
            }
        ));
        jT_personnel.setGridColor(new java.awt.Color(255, 255, 255));
        jT_personnel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jT_personnelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jT_personnel);

        jLabel1.setText("Nom :");

        jLabel2.setText("Prenom : ");

        jLabel3.setText("Adresse :");

        jLabel4.setText("Adres. lieu travail : ");

        jLabel5.setText("Poste :");

        jLabel6.setText("Numero badge :");

        jLabel7.setText("Id Supèrieur :");

        ajouter.setBackground(new java.awt.Color(0, 204, 204));
        ajouter.setText("Ajouter");
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });

        miseajour.setBackground(new java.awt.Color(0, 204, 204));
        miseajour.setText("Mettre à jour");
        miseajour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miseajourActionPerformed(evt);
            }
        });

        supprimer.setBackground(new java.awt.Color(0, 204, 204));
        supprimer.setText("Supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        voirpersonnelsupprimes.setBackground(new java.awt.Color(255, 153, 153));
        voirpersonnelsupprimes.setText("Voir les managers supprimés");
        voirpersonnelsupprimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voirpersonnelsupprimesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(voirpersonnelsupprimes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(miseajour, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(supprimer, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajouter)
                    .addComponent(miseajour)
                    .addComponent(supprimer))
                .addGap(18, 18, 18)
                .addComponent(voirpersonnelsupprimes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        boutonRestaurer.setBackground(new java.awt.Color(153, 204, 255));
        boutonRestaurer.setText("Restaurer le manager");
        boutonRestaurer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonRestaurerActionPerformed(evt);
            }
        });

        jT_idpersonnel.setText("0");

        message.setForeground(new java.awt.Color(0, 204, 204));
        message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        message.setText("Jlabel pour afficher des messages suivants les actions de l'utilisateur");

        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField8KeyReleased(evt);
            }
        });

        jLabel8.setText("Rechercher un manager : ");

        jLabel9.setText("Code manager");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jT_idpersonnel, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                    .addComponent(jT_num_badge)
                                    .addComponent(jT_poste)
                                    .addComponent(jT_adresse_travail)
                                    .addComponent(jT_adresse)
                                    .addComponent(jT_prenom)
                                    .addComponent(jT_nom)
                                    .addComponent(jT_idsup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                    .addComponent(jT_codemanager))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField8)))
                                .addGap(0, 17, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(boutonRestaurer, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(message)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(boutonRestaurer)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jT_idpersonnel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jT_nom, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jT_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jT_adresse, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jT_adresse_travail, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jT_poste, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jT_num_badge, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jT_idsup, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jT_codemanager, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jT_personnelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_personnelMouseClicked

        try{

            int j = jT_personnel.getSelectedRow();
            int i = jT_personnel.convertRowIndexToModel(j);

            TableModel tm = jT_personnel.getModel();

            jT_idpersonnel.setText(tm.getValueAt(i,0).toString());
            jT_nom.setText(tm.getValueAt(i,1).toString());
            jT_prenom.setText(tm.getValueAt(i,2).toString());
            jT_adresse.setText(tm.getValueAt(i,3).toString());
            jT_adresse_travail.setText(tm.getValueAt(i,4).toString());
            jT_poste.setText(tm.getValueAt(i,5).toString());
            jT_num_badge.setText(tm.getValueAt(i,6).toString());
            jT_idsup.setText(tm.getValueAt(i,7).toString());
            jT_codemanager.setText(tm.getValueAt(i,8).toString());
        }
        catch(Exception e){
            message.setText("Vous devez cliquez sur ligne !");
        }

    }//GEN-LAST:event_jT_personnelMouseClicked

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed

        int id_sup = 0 ;
        int id_personnel = 0 ;

        if(jT_nom.getText().equals("")  || jT_prenom.getText().equals("")  || jT_adresse.getText().equals("") || jT_adresse_travail.getText().equals("") || jT_poste.getText().equals("") || jT_num_badge.getText().equals("") || jT_idsup.getText().equals("") || jT_codemanager.getText().equals("")){
            message.setText("Tous les champs doivent être remplis");
        }
        else{
            try{
                id_sup = Integer.parseInt(jT_idsup.getText());

                int option = JOptionPane.showOptionDialog(
                    null,                             // Parent component
                    "Voulez-vous vraiment l'ajouter comme un nouveau manager ?",       // Message
                    "Confirmation",                  // Titre de la boîte de dialogue
                    JOptionPane.YES_NO_OPTION,        // Type de boîte de dialogue
                    JOptionPane.QUESTION_MESSAGE,    // Type d'icône
                    null,                             // Options personnalisées
                    null,                             // Option sélectionnée par défaut
                    null                              // Options de fermeture de la boîte de dialogue
                );

                if (option == JOptionPane.YES_OPTION) {

                    id_personnel = Miniprojetjava.baseDeDonnees.dernier_id_personne + 1 ;

                    Manager p = new Manager( id_personnel +"_"+ jT_idsup.getText() + "_" + jT_adresse.getText() + "_" + jT_adresse_travail.getText() + "_" + jT_poste.getText() + "_" + jT_num_badge.getText() + "_" + jT_nom.getText() + "_" + jT_prenom.getText() + "_0_" + jT_codemanager.getText());

                    DefaultTableModel model = (DefaultTableModel) jT_personnel.getModel();
                    model.addRow(new Object[]{p.idpersonnel, p.nom, p.prenom, p.adresse , p.adresselieutravail, p.poste, p.numerobadge, p.idsuperieur, p.codemanager});

                    Miniprojetjava.baseDeDonnees.ajouterManager_BD(p);

                    jT_idpersonnel.setText("0");
                    jT_nom.setText("");
                    jT_prenom.setText("");
                    jT_adresse.setText("");
                    jT_adresse_travail.setText("");
                    jT_poste.setText("");
                    jT_num_badge.setText("");
                    jT_idsup.setText("0");
                    jT_codemanager.setText("");

                    message.setText("Vous pouvez cliquez sur les entetes des colonnes, pour trier la table suivant cette colonne");
                }

                else{
                    message.setText("Vous pouvez cliquez sur les entetes des colonnes, pour trier la table suivant cette colonne");
                }

            }

            catch(Exception e){
                message.setText("L' ID du superieur doit être un entier");
            }
        }

    }//GEN-LAST:event_ajouterActionPerformed

    private void miseajourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miseajourActionPerformed

        int id_sup = 0 ;
        int id_personnel = 0 ;

        if(jT_personnel.getSelectedRow() == -1){
            if(jT_personnel.getRowCount() == 0){
                message.setText("La Tableau est encore vide !");
            }
            else{
                message.setText("Vous devriez d'abord selectionner une ligne du tableau");
            }
        }

        else{
            try{

                if(jT_nom.getText().equals("")  || jT_prenom.getText().equals("")  || jT_adresse.getText().equals("") || jT_adresse_travail.getText().equals("") || jT_poste.getText().equals("") || jT_num_badge.getText().equals("") || jT_idsup.getText().equals("") || jT_codemanager.getText().equals("")){
                    message.setText("Tous les champs doivent être remplis");
                }
                else{

                    id_sup = Integer.parseInt(jT_idsup.getText());

                    int option = JOptionPane.showOptionDialog(
                        null,                             // Parent component
                        "Voulez-vous vraiment modifier ce manager ?",       // Message
                        "Confirmation",                  // Titre de la boîte de dialogue
                        JOptionPane.YES_NO_OPTION,        // Type de boîte de dialogue
                        JOptionPane.QUESTION_MESSAGE,    // Type d'icône
                        null,                             // Options personnalisées
                        null,                             // Option sélectionnée par défaut
                        null                              // Options de fermeture de la boîte de dialogue
                    );

                    if (option == JOptionPane.YES_OPTION) {

                        id_personnel = Integer.parseInt(jT_idpersonnel.getText());

                        Manager p = new Manager( id_personnel +"_"+ jT_idsup.getText() + "_" + jT_adresse.getText() + "_" + jT_adresse_travail.getText() + "_" + jT_poste.getText() + "_" + jT_num_badge.getText() + "_" + jT_nom.getText() + "_" + jT_prenom.getText() + "_0_" + jT_codemanager.getText());

                        DefaultTableModel model = (DefaultTableModel) jT_personnel.getModel();

                        model.setValueAt(p.idpersonnel, jT_personnel.getSelectedRow(), 0);
                        model.setValueAt(p.nom, jT_personnel.getSelectedRow(), 1);
                        model.setValueAt(p.prenom, jT_personnel.getSelectedRow(), 2);
                        model.setValueAt(p.adresse, jT_personnel.getSelectedRow(), 3);
                        model.setValueAt(p.adresselieutravail, jT_personnel.getSelectedRow(), 4);
                        model.setValueAt(p.poste, jT_personnel.getSelectedRow(), 5);
                        model.setValueAt(p.numerobadge, jT_personnel.getSelectedRow(), 6);
                        model.setValueAt(p.idsuperieur, jT_personnel.getSelectedRow(), 7);
                        model.setValueAt(p.codemanager, jT_personnel.getSelectedRow(), 8);

                        //model.addRow(new Object[]{p.idpersonnel, p.nom, p.prenom, p.adresse , p.adresselieutravail, p.poste, p.numerobadge, p.idsuperieur});

                        Miniprojetjava.baseDeDonnees.modifierManager_BD(id_personnel, p);

                        jT_idpersonnel.setText("0");
                        jT_nom.setText("");
                        jT_prenom.setText("");
                        jT_adresse.setText("");
                        jT_adresse_travail.setText("");
                        jT_poste.setText("");
                        jT_num_badge.setText("");
                        jT_idsup.setText("0");
                        jT_codemanager.setText("");

                        message.setText("Vous pouvez cliquez sur les entetes des colonnes, pour trier la table suivant cette colonne");
                    }

                    else{
                        message.setText("Vous pouvez cliquez sur les entetes des colonnes, pour trier la table suivant cette colonne");
                    }

                }

            }

            catch(Exception e){
                message.setText("L' ID du superieur doit être un entier");
            }
        }

    }//GEN-LAST:event_miseajourActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed

        int id_personnel = Integer.parseInt(jT_idpersonnel.getText());

        System.out.println(id_personnel);

        DefaultTableModel model = (DefaultTableModel) jT_personnel.getModel();

        if(jT_personnel.getSelectedRow() == -1){
            if(jT_personnel.getRowCount() == 0){
                message.setText("La facture est encore vide !");
            }
            else{
                message.setText("Vous devriez d'abord selectionner un article de la facture");
            }
        }

        else{

            int j = jT_personnel.getSelectedRow();
            int i = jT_personnel.convertRowIndexToModel(j);

            Miniprojetjava.baseDeDonnees.supprimerManger_BD(id_personnel);
            model.removeRow(i);

            jT_idpersonnel.setText("0");
            jT_nom.setText("");
            jT_prenom.setText("");
            jT_adresse.setText("");
            jT_adresse_travail.setText("");
            jT_poste.setText("");
            jT_num_badge.setText("");
            jT_idsup.setText("0");
            jT_codemanager.setText("");

            message.setText("Cliquez sur le bouton ajouter pour ajouter un produit à la facture");

        }
    }//GEN-LAST:event_supprimerActionPerformed

    private void voirpersonnelsupprimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voirpersonnelsupprimesActionPerformed

        if( ! desactivationbouton){

            String[][] tabperSup = Miniprojetjava.baseDeDonnees.getmanagerSupprimes();

            DefaultTableModel model = (DefaultTableModel) jT_personnel.getModel();

            model.setRowCount(0);

            String[] columnNames = {"Id personnel", "Nom", "Prenom", "Adresse", "Adresse lieu travail", "Poste", "Num badge", "Id superieur", "Code manager"};

            model.setDataVector(tabperSup, columnNames );

            boutonRestaurer.setVisible(true);

            voirpersonnelsupprimes.setText("Revenir en arrière");

            ajouter.setEnabled(desactivationbouton);
            miseajour.setEnabled(desactivationbouton);
            supprimer.setEnabled(desactivationbouton);

            desactivationbouton = true ;
        }
        else{

            String[][] tabperSup = Miniprojetjava.baseDeDonnees.getmanagerNonSupprimes();

            DefaultTableModel model = (DefaultTableModel) jT_personnel.getModel();

            model.setRowCount(0);

            String[] columnNames = {"Id personnel", "Nom", "Prenom", "Adresse", "Adresse lieu travail", "Poste", "Num badge", "Id superieur", "Code manager"};

            model.setDataVector(tabperSup, columnNames );

            boutonRestaurer.setVisible(false);

            voirpersonnelsupprimes.setText("Voir les managers supprimés");

            ajouter.setEnabled(desactivationbouton);
            miseajour.setEnabled(desactivationbouton);
            supprimer.setEnabled(desactivationbouton);

            desactivationbouton = false ;
        }

    }//GEN-LAST:event_voirpersonnelsupprimesActionPerformed

    private void boutonRestaurerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonRestaurerActionPerformed

        int id_personnel = Integer.parseInt(jT_idpersonnel.getText());

        System.out.println(id_personnel);

        DefaultTableModel model = (DefaultTableModel) jT_personnel.getModel();

        if(jT_personnel.getSelectedRow() == -1){
            if(jT_personnel.getRowCount() == 0){
                message.setText("La facture est encore vide !");
            }
            else{
                message.setText("Vous devriez d'abord selectionner un article de la facture");
            }
        }

        else{

            int j = jT_personnel.getSelectedRow();
            int i = jT_personnel.convertRowIndexToModel(j);

            Miniprojetjava.baseDeDonnees.restaurerManagerSupprime(id_personnel);
            model.removeRow(i);

            jT_idpersonnel.setText("0");
            jT_nom.setText("");
            jT_prenom.setText("");
            jT_adresse.setText("");
            jT_adresse_travail.setText("");
            jT_poste.setText("");
            jT_num_badge.setText("");
            jT_idsup.setText("0");
            jT_codemanager.setText("");

            message.setText("Cliquez sur le bouton ajouter pour ajouter un produit à la facture");

        }

    }//GEN-LAST:event_boutonRestaurerActionPerformed

    private void jTextField8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyReleased
        JPanel_Caissier.rechercheAutomatique(jT_personnel, jTextField8, message);

        if(message.getText().equals("")){
            message.setText("Vous pouvez cliquez sur les entetes des colonnes, pour trier la table suivant cette colonne");
        }
    }//GEN-LAST:event_jTextField8KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter;
    private javax.swing.JButton boutonRestaurer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jT_adresse;
    private javax.swing.JTextField jT_adresse_travail;
    private javax.swing.JTextField jT_codemanager;
    private javax.swing.JTextField jT_idpersonnel;
    private javax.swing.JTextField jT_idsup;
    private javax.swing.JTextField jT_nom;
    private javax.swing.JTextField jT_num_badge;
    private javax.swing.JTable jT_personnel;
    private javax.swing.JTextField jT_poste;
    private javax.swing.JTextField jT_prenom;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel message;
    private javax.swing.JButton miseajour;
    private javax.swing.JButton supprimer;
    private javax.swing.JButton voirpersonnelsupprimes;
    // End of variables declaration//GEN-END:variables
}
