package graphiquepackage;

import com.mycompany.miniprojetjava.Manager;
import java.awt.BorderLayout;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author semje
 */
public class JPanel_Manager extends javax.swing.JPanel {

    /**
     * Creates new form JPanel_Manager
     */
    public JPanel_Manager(Manager m) {
        initComponents();
        
        LocalDate date1 = LocalDate.now(); // date actuelle
        
        jL_nomManager.setText(m.nom + " " + m.prenom);
        jL_date.setText(date1.toString());
        
        jPanel_manager_main.setLayout(new BorderLayout());
        jPanel_manager_main.removeAll();
        GestionPersonnel jp_gp = new GestionPersonnel();
        jPanel_manager_main.add(jp_gp);
        jPanel_manager_main.revalidate();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        boutonGererManager = new javax.swing.JButton();
        boutonGererCaissiers = new javax.swing.JButton();
        boutonGererPersonnels = new javax.swing.JButton();
        boutonGererClient = new javax.swing.JButton();
        boutonGererPointvente = new javax.swing.JButton();
        boutonGererProduits = new javax.swing.JButton();
        boutonApercuvente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel_manager_main = new javax.swing.JPanel();
        jL_nomManager = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jL_date = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1355, 780));

        boutonGererManager.setBackground(new java.awt.Color(0, 204, 204));
        boutonGererManager.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        boutonGererManager.setForeground(new java.awt.Color(102, 102, 102));
        boutonGererManager.setText("Gérer les Managers");
        boutonGererManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonGererManagerActionPerformed(evt);
            }
        });

        boutonGererCaissiers.setBackground(new java.awt.Color(0, 204, 204));
        boutonGererCaissiers.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        boutonGererCaissiers.setForeground(new java.awt.Color(102, 102, 102));
        boutonGererCaissiers.setText("Gérer les Caissier(e)s");
        boutonGererCaissiers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonGererCaissiersActionPerformed(evt);
            }
        });

        boutonGererPersonnels.setBackground(new java.awt.Color(0, 204, 204));
        boutonGererPersonnels.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        boutonGererPersonnels.setForeground(new java.awt.Color(102, 102, 102));
        boutonGererPersonnels.setText("Gérer les Personnels");
        boutonGererPersonnels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonGererPersonnelsActionPerformed(evt);
            }
        });

        boutonGererClient.setBackground(new java.awt.Color(0, 204, 204));
        boutonGererClient.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        boutonGererClient.setForeground(new java.awt.Color(102, 102, 102));
        boutonGererClient.setText("Gérer les Clients");
        boutonGererClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonGererClientActionPerformed(evt);
            }
        });

        boutonGererPointvente.setBackground(new java.awt.Color(0, 204, 204));
        boutonGererPointvente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        boutonGererPointvente.setForeground(new java.awt.Color(102, 102, 102));
        boutonGererPointvente.setText("Gérer les Point de vente");
        boutonGererPointvente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonGererPointventeActionPerformed(evt);
            }
        });

        boutonGererProduits.setBackground(new java.awt.Color(0, 204, 204));
        boutonGererProduits.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        boutonGererProduits.setForeground(new java.awt.Color(102, 102, 102));
        boutonGererProduits.setText("Gérer les Produits");
        boutonGererProduits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonGererProduitsActionPerformed(evt);
            }
        });

        boutonApercuvente.setBackground(new java.awt.Color(255, 153, 153));
        boutonApercuvente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        boutonApercuvente.setForeground(new java.awt.Color(102, 102, 102));
        boutonApercuvente.setText("Apercu des ventes");
        boutonApercuvente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonApercuventeActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("./fichiers/boutoneteindre2.png")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Deconnexion");

        jLabel2.setIcon(new javax.swing.ImageIcon("./fichiers/manager2.png")); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe Script", 0, 20)); // NOI18N
        jLabel15.setText("Management");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel18))
                .addGap(107, 107, 107))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boutonGererCaissiers, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addComponent(boutonGererPersonnels, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addComponent(boutonGererManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boutonGererClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boutonGererPointvente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boutonGererProduits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boutonApercuvente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15)
                        .addGap(50, 50, 50)))
                .addComponent(boutonGererPersonnels, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boutonGererCaissiers)
                .addGap(18, 18, 18)
                .addComponent(boutonGererManager, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boutonGererClient)
                .addGap(18, 18, 18)
                .addComponent(boutonGererPointvente)
                .addGap(18, 18, 18)
                .addComponent(boutonGererProduits)
                .addGap(18, 18, 18)
                .addComponent(boutonApercuvente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGap(68, 68, 68))
        );

        jPanel_manager_main.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_manager_main.setPreferredSize(new java.awt.Dimension(1010, 650));

        javax.swing.GroupLayout jPanel_manager_mainLayout = new javax.swing.GroupLayout(jPanel_manager_main);
        jPanel_manager_main.setLayout(jPanel_manager_mainLayout);
        jPanel_manager_mainLayout.setHorizontalGroup(
            jPanel_manager_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        jPanel_manager_mainLayout.setVerticalGroup(
            jPanel_manager_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        jL_nomManager.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jL_nomManager.setText("SEM Jean Christopher");

        jLabel4.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        jLabel4.setText("Bienvenue à vous M. Mr ");

        jL_date.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jL_date.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jL_date.setText("Date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_manager_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jL_nomManager, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jL_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jL_nomManager, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel_manager_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jL_date, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void boutonGererManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonGererManagerActionPerformed
        jPanel_manager_main.setLayout(new BorderLayout());
        jPanel_manager_main.removeAll();
        GestionManager jp_gc = new GestionManager();
        jPanel_manager_main.add(jp_gc);
        jPanel_manager_main.revalidate();
    }//GEN-LAST:event_boutonGererManagerActionPerformed

    private void boutonGererCaissiersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonGererCaissiersActionPerformed
        jPanel_manager_main.setLayout(new BorderLayout());
        jPanel_manager_main.removeAll();
        GestionCaissier jp_gc = new GestionCaissier();
        jPanel_manager_main.add(jp_gc);
        jPanel_manager_main.revalidate();
    }//GEN-LAST:event_boutonGererCaissiersActionPerformed

    private void boutonGererPersonnelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonGererPersonnelsActionPerformed
        jPanel_manager_main.setLayout(new BorderLayout());
        jPanel_manager_main.removeAll();
        GestionPersonnel jp_gp = new GestionPersonnel();
        jPanel_manager_main.add(jp_gp);
        jPanel_manager_main.revalidate();
    }//GEN-LAST:event_boutonGererPersonnelsActionPerformed

    private void boutonGererClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonGererClientActionPerformed
        jPanel_manager_main.setLayout(new BorderLayout());
        jPanel_manager_main.removeAll();
        GestionClient jp_gp = new GestionClient();
        jPanel_manager_main.add(jp_gp);
        jPanel_manager_main.revalidate();
    }//GEN-LAST:event_boutonGererClientActionPerformed

    private void boutonGererPointventeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonGererPointventeActionPerformed
        jPanel_manager_main.setLayout(new BorderLayout());
        jPanel_manager_main.removeAll();
        GestionPointvente jp_gp = new GestionPointvente();
        jPanel_manager_main.add(jp_gp);
        jPanel_manager_main.revalidate();
    }//GEN-LAST:event_boutonGererPointventeActionPerformed

    private void boutonGererProduitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonGererProduitsActionPerformed
        jPanel_manager_main.setLayout(new BorderLayout());
        jPanel_manager_main.removeAll();
        GestionProduit jp_gp = new GestionProduit();
        jPanel_manager_main.add(jp_gp);
        jPanel_manager_main.revalidate();
    }//GEN-LAST:event_boutonGererProduitsActionPerformed

    private void boutonApercuventeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonApercuventeActionPerformed
        jPanel_manager_main.setLayout(new BorderLayout());
        jPanel_manager_main.removeAll();
        ApercuVente jp_gp = new ApercuVente();
        jPanel_manager_main.add(jp_gp);
        jPanel_manager_main.revalidate();
    }//GEN-LAST:event_boutonApercuventeActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
        
        int option = JOptionPane.showOptionDialog(
                    null,                             // Parent component
                    "Voulez-vous vraiment fermer cette page ?",       // Message
                    "Confirmation",                  // Titre de la boîte de dialogue
                    JOptionPane.YES_NO_OPTION,        // Type de boîte de dialogue
                    JOptionPane.QUESTION_MESSAGE,    // Type d'icône
                    null,                             // Options personnalisées
                    null,                             // Option sélectionnée par défaut
                    null                              // Options de fermeture de la boîte de dialogue
                );

        if (option == JOptionPane.YES_OPTION) {

            Home.jPanel_main.setLayout(new BorderLayout());
            Home.jPanel_main.removeAll();
            JPanel_Home jp_home = new JPanel_Home();
            Home.jPanel_main.add(jp_home);
            Home.jPanel_main.revalidate();

        }
    }//GEN-LAST:event_jLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonApercuvente;
    private javax.swing.JButton boutonGererCaissiers;
    private javax.swing.JButton boutonGererClient;
    private javax.swing.JButton boutonGererManager;
    private javax.swing.JButton boutonGererPersonnels;
    private javax.swing.JButton boutonGererPointvente;
    private javax.swing.JButton boutonGererProduits;
    private javax.swing.JLabel jL_date;
    private javax.swing.JLabel jL_nomManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_manager_main;
    // End of variables declaration//GEN-END:variables
}
