package graphiquepackage;

import com.mycompany.miniprojetjava.Caissier;
import com.mycompany.miniprojetjava.Miniprojetjava;
import com.mycompany.miniprojetjava.PointVente;
import com.mycompany.miniprojetjava.Vente;
import java.awt.BorderLayout;
import java.awt.Color;
import java.text.MessageFormat;
import java.time.LocalDate;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author semje
 */
public class JPanel_Caissier extends javax.swing.JPanel {

    /**
     * Creates new form JPanel_Caissier
     */
    
    double operande1 = 0.0 ;
    double operande2 = 0.0 ;
    double resultat = 0.0 ;
    String entree = "" ;
    String operateur = "";
    
    Caissier le_caissier ;
    
    String date ;
    
    int id_client = 0 ;
    
    int id_pointvente = 0 ;
    
    
    public JPanel_Caissier(Caissier c, int pointvente) {
        initComponents();
        
        PointVente pv = Miniprojetjava.baseDeDonnees.getPointventeById(pointvente);
        jL_pointvente.setText(pv.nom.toUpperCase());
        
        LocalDate date1 = LocalDate.now(); // date actuelle
        
        date = date1.toString();
        
        jL_date.setText("Date : " + date);
        
        le_caissier = c ;
        id_pointvente = pointvente ;
        
        jL_nomCaissier.setText(le_caissier.nom.toUpperCase() + " " + le_caissier.prenom);
        
        Miniprojetjava.baseDeDonnees.afficherListeCaissier_BD();
        
        jT_produit.disable();
        jT_prix.disable();
        jT_id_produit.disable();
        
        jL_operateur.setText(operateur);
        jL_entree.setText(entree);
        
        for(int i=0 ; i < Miniprojetjava.baseDeDonnees.liste_Type_BD.size() ; i++ ){
            jC_type.addItem(Miniprojetjava.baseDeDonnees.liste_Type_BD.get(i).type);
        }
        
        //jC_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "noonman", "orphe", "second", "kowane" }));
        
        DefaultTableModel model = (DefaultTableModel) resultatRecherchePdt.getModel();
        
        for(int i=0 ; i < Miniprojetjava.baseDeDonnees.liste_Produits_BD.size() ; i++ ){
            model.addRow(new Object[]{Miniprojetjava.baseDeDonnees.liste_Produits_BD.get(i).idproduit, Miniprojetjava.baseDeDonnees.liste_Produits_BD.get(i).nom,Miniprojetjava.baseDeDonnees.liste_Produits_BD.get(i).prix, Miniprojetjava.baseDeDonnees.liste_Produits_BD.get(i).paysorigine});
        }
        
        resultatRecherchePdt.setAutoCreateRowSorter(true);
        
        DefaultTableModel model1 = (DefaultTableModel) resultatRechercheClient.getModel();
        
        for(int i=0 ; i < Miniprojetjava.baseDeDonnees.liste_Clients_BD.size() ; i++ ){
            model1.addRow(new Object[]{Miniprojetjava.baseDeDonnees.liste_Clients_BD.get(i).idclient, Miniprojetjava.baseDeDonnees.liste_Clients_BD.get(i).numerocartefidelite, Miniprojetjava.baseDeDonnees.liste_Clients_BD.get(i).nom, Miniprojetjava.baseDeDonnees.liste_Clients_BD.get(i).prenom});
        }
        
        resultatRechercheClient.setAutoCreateRowSorter(true);
        
    }
    
    public static void rechercheAutomatique(JTable jt, JTextField jtf, JLabel jl){
        DefaultTableModel dtm = (DefaultTableModel) jt.getModel();
        String mot = jtf.getText().trim();
        
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(dtm);
        jt.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(mot));
        
        int nbre = jt.getRowCount();
        
        if(nbre == 0){
            jl.setForeground(Color.red);
            jl.setText("Aucun item corrspond à ce nom");
        }
        
        if(nbre > 0){
            jl.setForeground( new Color(0,102,0));
            jl.setText("Resultats correspondants : " + nbre);
        }
        
        if(mot.equals("")){
            jl.setText("");
        }
    }
    
    public static void calculTotalFacture(JTable facture, JLabel jl){
        int nbreligne = facture.getRowCount();
        double total = 0.0 ;
        
        for(int i=0 ; i<nbreligne ; i++){
            
            total = total + Double.parseDouble(facture.getValueAt(i, 4).toString());
        }
        
        jl.setText("Total : "+total+" euros");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jL_operateur = new javax.swing.JLabel();
        jL_entree = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        facture = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jL_total = new javax.swing.JLabel();
        jT_fidelite = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomproduit = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultatRecherchePdt = new javax.swing.JTable();
        inforechercheproduit = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rechercheclient = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultatRechercheClient = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        inforechercheclient = new javax.swing.JLabel();
        boutonAjouter = new javax.swing.JButton();
        Boutonmisejour = new javax.swing.JButton();
        boutonSupp = new javax.swing.JButton();
        jT_prix = new javax.swing.JTextField();
        jT_remise = new javax.swing.JTextField();
        jC_type = new javax.swing.JComboBox<>();
        jT_qtitepoids = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        message = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jT_produit = new javax.swing.JTextField();
        prix = new javax.swing.JLabel();
        jT_id_produit = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jL_nomCaissier = new javax.swing.JLabel();
        jL_date = new javax.swing.JLabel();
        jL_pointvente = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1355, 780));

        jPanel5.setBackground(new java.awt.Color(255, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jL_operateur.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jL_operateur.setForeground(new java.awt.Color(0, 153, 153));
        jL_operateur.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_operateur.setText("-");

        jL_entree.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jL_entree.setForeground(new java.awt.Color(102, 102, 102));
        jL_entree.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jL_entree.setText("99999999999999");

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel11.setText("7 digits à taper aux max");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jL_entree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jL_operateur, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jL_operateur, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jL_entree, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        jButton2.setBackground(new java.awt.Color(255, 204, 153));
        jButton2.setText("1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 204, 153));
        jButton6.setText("2");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 204, 153));
        jButton7.setText("3");
        jButton7.setToolTipText("");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 204, 153));
        jButton8.setText("4");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(255, 204, 153));
        jButton9.setText("5");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(255, 204, 153));
        jButton10.setText("6");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(255, 204, 153));
        jButton11.setText("7");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(255, 204, 153));
        jButton12.setText("8");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(255, 204, 153));
        jButton13.setText("9");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(0, 204, 204));
        jButton14.setText("+");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(255, 204, 153));
        jButton15.setText("0");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(0, 204, 204));
        jButton16.setText("*");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setBackground(new java.awt.Color(0, 204, 204));
        jButton17.setText("-");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setBackground(new java.awt.Color(0, 204, 204));
        jButton18.setText("=");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setBackground(new java.awt.Color(0, 204, 204));
        jButton19.setText("/");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setBackground(new java.awt.Color(153, 204, 255));
        jButton20.setText("Reset");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton21.setBackground(new java.awt.Color(153, 204, 255));
        jButton21.setText("Effacer");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton22.setBackground(new java.awt.Color(153, 204, 255));
        jButton22.setText(".");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel14.setIcon(new javax.swing.ImageIcon("./fichiers/piece.png")); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe Script", 0, 36)); // NOI18N
        jLabel15.setText("Caisse");

        jLabel17.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("f(x) | Calculatrice");

        jLabel16.setIcon(new javax.swing.ImageIcon("./fichiers/boutoneteindre2.png")); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Deconnexion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(17, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(jLabel16))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(49, 49, 49)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        facture.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id prdt", "Nom prdt", "Quantité/poids", "Type", "Prix"
            }
        ));
        facture.setGridColor(new java.awt.Color(255, 255, 255));
        facture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                factureMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(facture);

        jButton5.setBackground(new java.awt.Color(255, 204, 204));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(153, 153, 153));
        jButton5.setText("Encaisser et imprimer la facture");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("SimSun-ExtB", 0, 36)); // NOI18N
        jLabel9.setText("Facture");

        jL_total.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jL_total.setText("Total : 0 euros");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jL_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addGap(67, 67, 67)
                        .addComponent(jT_fidelite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jT_fidelite, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL_total)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 102, 102));
        jButton1.setText("Nouvel achat");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Recherche produit"));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Nom produit");

        nomproduit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomproduitKeyReleased(evt);
            }
        });

        resultatRecherchePdt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        resultatRecherchePdt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id produit", "Nom", "Prix unit. (ou /kg)", "Pays d'origine"
            }
        ));
        resultatRecherchePdt.setGridColor(new java.awt.Color(255, 255, 255));
        resultatRecherchePdt.setRowHeight(25);
        resultatRecherchePdt.setSelectionBackground(new java.awt.Color(153, 255, 204));
        resultatRecherchePdt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultatRecherchePdtMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(resultatRecherchePdt);

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 10)); // NOI18N
        jLabel7.setText("Ciquez sur l'entête d'une colonne ( nom, pays etc...) pour trier le tableau suivant cette colonne");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(inforechercheproduit, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(nomproduit, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nomproduit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(7, 7, 7)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inforechercheproduit, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Ajouter un client (pas obligatoire)"));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Num crte Fidl");

        rechercheclient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rechercheclientKeyReleased(evt);
            }
        });

        resultatRechercheClient.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        resultatRechercheClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Client", "Num Carte Fdl", "Nom", "Prenom"
            }
        ));
        resultatRechercheClient.setGridColor(new java.awt.Color(255, 255, 255));
        resultatRechercheClient.setRowHeight(25);
        resultatRechercheClient.setSelectionBackground(new java.awt.Color(153, 255, 204));
        resultatRechercheClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultatRechercheClientMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(resultatRechercheClient);

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 10)); // NOI18N
        jLabel8.setText("Ciquez sur l'entête d'une colonne ( nom, prenom etc...) pour trier le tableau suivant cette colonne");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rechercheclient, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8)
                    .addComponent(inforechercheclient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rechercheclient, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inforechercheclient, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        boutonAjouter.setBackground(new java.awt.Color(0, 204, 204));
        boutonAjouter.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        boutonAjouter.setForeground(new java.awt.Color(255, 102, 102));
        boutonAjouter.setText("Ajouter");
        boutonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAjouterActionPerformed(evt);
            }
        });

        Boutonmisejour.setBackground(new java.awt.Color(0, 204, 204));
        Boutonmisejour.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Boutonmisejour.setForeground(new java.awt.Color(255, 102, 102));
        Boutonmisejour.setText("Mettre à jour");
        Boutonmisejour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonmisejourActionPerformed(evt);
            }
        });

        boutonSupp.setBackground(new java.awt.Color(0, 204, 204));
        boutonSupp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        boutonSupp.setForeground(new java.awt.Color(255, 102, 102));
        boutonSupp.setText("Supprimer");
        boutonSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonSuppActionPerformed(evt);
            }
        });

        jT_prix.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jT_prix.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jT_prix.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jT_remise.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jT_remise.setText("0");
        jT_remise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 153)));

        jC_type.setBackground(new java.awt.Color(255, 204, 153));
        jC_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC_typeActionPerformed(evt);
            }
        });

        jT_qtitepoids.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jT_qtitepoids.setText("0");
        jT_qtitepoids.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 153)));

        jLabel3.setText("Nom produit");

        jLabel4.setText("Type");

        jLabel5.setText("Quatité / poids");

        jLabel6.setText("Remise (%)");

        message.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        message.setForeground(new java.awt.Color(255, 51, 0));
        message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        message.setText("Cliquez sur le bouton ajouter pour ajouter un produit à la facture");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Recherchez un produit, cliquez dessus pour le selectionner, entrez la quantité ou le poids, puis appuyez sur le bouton Ajouter pour ajouter le produit selectionné à la facture");

        jT_produit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jT_produit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jT_produit.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        prix.setText("Prix unit. ou /kg");

        jT_id_produit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jT_id_produit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jT_id_produit.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel12.setText("Id prdt");

        jLabel13.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        jLabel13.setText("Bienvenue à vous  M. Mr");

        jL_nomCaissier.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jL_nomCaissier.setText("SEM Jean Christopher");

        jL_date.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jL_date.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jL_date.setText("Date");

        jL_pointvente.setForeground(new java.awt.Color(0, 204, 204));
        jL_pointvente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jL_pointvente.setText("Point de vante");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel12))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(jT_id_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jT_produit)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jT_prix)
                                            .addComponent(prix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jC_type, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(44, 44, 44)
                                                .addComponent(jLabel4)))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jT_qtitepoids))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jT_remise, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(boutonAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Boutonmisejour, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(boutonSupp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13))
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_nomCaissier, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jL_pointvente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jL_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jL_pointvente))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_nomCaissier)
                    .addComponent(jL_date, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(prix)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jT_prix, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jT_qtitepoids, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jT_remise, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jT_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jC_type, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jT_id_produit, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boutonAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boutonmisejour, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boutonSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(message)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nomproduitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomproduitKeyReleased
        JPanel_Caissier.rechercheAutomatique(resultatRecherchePdt, nomproduit, inforechercheproduit);
    }//GEN-LAST:event_nomproduitKeyReleased

    private void jC_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jC_typeActionPerformed

    private void rechercheclientKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rechercheclientKeyReleased
        JPanel_Caissier.rechercheAutomatique(resultatRechercheClient, rechercheclient, inforechercheclient);
    }//GEN-LAST:event_rechercheclientKeyReleased

    private void boutonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAjouterActionPerformed
        
        double quantite ;
        double remise ;
        double prix ;
        
        try{
            quantite = Double.parseDouble(jT_qtitepoids.getText());
            remise = Double.parseDouble(jT_remise.getText());
            
            
            if(jT_produit.getText().equals("")){
                
                message.setText("Aucun produit n'a encore été selectioné");
                
            }
            else{
                
                if(quantite != 0){
                    prix = Double.parseDouble(jT_prix.getText());
                    DefaultTableModel model = (DefaultTableModel) facture.getModel();
                    model.addRow(new Object[]{jT_id_produit.getText(), jT_produit.getText(), quantite , jC_type.getSelectedItem().toString() , (prix - ((prix*remise)/100))*quantite});
                    
                    jT_id_produit.setText("");
                    jT_produit.setText("");
                    jT_prix.setText("");
                    jT_qtitepoids.setText("0");
                    jT_remise.setText("0");
                    
                    calculTotalFacture(facture, jL_total);
                    
                    jC_type.setSelectedItem("autre");
                    
                    message.setText("Cliquez sur le bouton ajouter pour ajouter un produit à la facture");

                }
                else{
                    message.setText("La quantité doit être different 0");
                }
                
            }
            
        }
        
        catch(Exception e){
            message.setText("Verifiez la valeur de la quantité ou de la remise");
        }
        
        
        
    }//GEN-LAST:event_boutonAjouterActionPerformed

    private void resultatRecherchePdtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultatRecherchePdtMouseClicked
        try{
            
            int j = resultatRecherchePdt.getSelectedRow(); 
            int i = resultatRecherchePdt.convertRowIndexToModel(j);
            
            TableModel tm = resultatRecherchePdt.getModel();
            jT_id_produit.setText(tm.getValueAt(i,0).toString());
            jT_produit.setText(tm.getValueAt(i,1).toString());
            jT_prix.setText(tm.getValueAt(i,2).toString());
            jT_qtitepoids.setText("1");
        }
        catch(Exception e){
            message.setText("Vous devez cliquez sur ligne !");
        }
    }//GEN-LAST:event_resultatRecherchePdtMouseClicked

    private void resultatRechercheClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultatRechercheClientMouseClicked
        
        String fidelite ;
        
        try{
             
            int j = resultatRechercheClient.getSelectedRow(); 
            int i = resultatRechercheClient.convertRowIndexToModel(j);
            
            TableModel tm = resultatRechercheClient.getModel();
            
            id_client = Integer.parseInt(tm.getValueAt(i,0).toString());
            fidelite = tm.getValueAt(i,1).toString();
            
            jT_fidelite.setText("Cient : "+fidelite);
            
            inforechercheclient.setForeground( new Color(0,102,0));
            inforechercheclient.setText("Le client a bien été ajouté !");
            
        }
        catch(Exception e){
            message.setText("Vous devez cliquez sur ligne !");
        }
    }//GEN-LAST:event_resultatRechercheClientMouseClicked

    private void BoutonmisejourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonmisejourActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) facture.getModel();
        
        if(facture.getSelectedRow() == -1){
            if(facture.getRowCount() == 0){
                message.setText("La facture est encore vide !");
            }
            else{
                message.setText("Vous devriez d'abord selectionner un article de la facture");
            }
        }
        
        else{
            
            double quantite ;
            double remise ;
            double prix ;

            try{
                quantite = Double.parseDouble(jT_qtitepoids.getText());
                remise = Double.parseDouble(jT_remise.getText());


                if(jT_produit.getText().equals("")){

                    message.setText("Aucun produit n'a encore été selectioné");

                }
                else{

                    if(quantite != 0){
                        
                        prix = Double.parseDouble(jT_prix.getText());
                        
                        model.setValueAt(jT_id_produit.getText(), facture.getSelectedRow(), 0);
                        model.setValueAt(jT_produit.getText(), facture.getSelectedRow(), 1);
                        model.setValueAt(quantite, facture.getSelectedRow(), 2);
                        model.setValueAt(jC_type.getSelectedItem().toString(), facture.getSelectedRow(), 3);
                        model.setValueAt((prix - ((prix*remise)/100))*quantite, facture.getSelectedRow(), 4);
                        
                        jT_id_produit.setText("");
                        jT_produit.setText("");
                        jT_prix.setText("");
                        jT_qtitepoids.setText("0");
                        jT_remise.setText("0");
                        
                        calculTotalFacture(facture, jL_total);
                        
                        jC_type.setSelectedItem("autre");
                        
                        message.setText("Cliquez sur le bouton ajouter pour ajouter un produit à la facture");

                    }
                    else{
                        message.setText("La quantité doit être different 0");
                    }

                }

            }

            catch(Exception e){
                message.setText("Verifiez la valeur de la quantité ou de la remise");
            }
        }
        
        
    }//GEN-LAST:event_BoutonmisejourActionPerformed

    private void factureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_factureMouseClicked
        
        String q ;
        String p ;
        
        try{
            
            int j = facture.getSelectedRow(); 
            int i = facture.convertRowIndexToModel(j);
            TableModel tm = facture.getModel();
            q = tm.getValueAt(i,2).toString();
            p = tm.getValueAt(i,4).toString();
            
            jT_id_produit.setText(tm.getValueAt(i,0).toString());
            jT_produit.setText(tm.getValueAt(i,1).toString());
            jT_qtitepoids.setText(q);
            jC_type.setSelectedItem(tm.getValueAt(i,3));
            jT_prix.setText(""+(Double.parseDouble(p) / Double.parseDouble(q)));
        }
        catch(Exception e){
            message.setText("Vous devez cliquez sur ligne !");
        }
        
    }//GEN-LAST:event_factureMouseClicked

    private void boutonSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonSuppActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) facture.getModel();
        
        if(facture.getSelectedRow() == -1){
            if(facture.getRowCount() == 0){
                message.setText("La facture est encore vide !");
            }
            else{
                message.setText("Vous devriez d'abord selectionner un article de la facture");
            }
        }
        
        else{
            
            int j = facture.getSelectedRow(); 
            int i = facture.convertRowIndexToModel(j);
            
            model.removeRow(i);
                    
            jT_id_produit.setText("");
            jT_produit.setText("");
            jT_prix.setText("");
            jT_qtitepoids.setText("0");
            jT_remise.setText("0");

            calculTotalFacture(facture, jL_total);
            
            jC_type.setSelectedItem("autre");

            message.setText("Cliquez sur le bouton ajouter pour ajouter un produit à la facture");
            
        }
        //calculTotalFacture(facture, jL_total);
        //message.setText("Cliquez sur le bouton ajouter pour ajouter un produit à la facture");
    }//GEN-LAST:event_boutonSuppActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int choix = JOptionPane.showConfirmDialog(null, "Voulez vous vraiment passer à un nouvel achat ? \n    (Les données de cette page seront perdues)", "Confirmation", JOptionPane.YES_NO_OPTION);
        
        if(choix == JOptionPane.YES_OPTION){
            this.setLayout(new BorderLayout());
            this.removeAll();
            JPanel_Caissier jp_caissier = new JPanel_Caissier(le_caissier, id_pointvente);
            this.add(jp_caissier);
            this.revalidate();
        }else{
            //on fait rien du tout
        }
        
        
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        if(entree.length() != 0){
            
            if(operateur.length() == 0){
                try{
                    operande1 = Double.parseDouble(entree.replace(",", "."));

                    operateur = "/" ;
                    jL_operateur.setText(operateur);

                    entree = "";
                    jL_entree.setText(entree);
                }
                catch(Exception e){
                    operande1 = 0.0 ;
                    operande2 = 0.0 ;
                    resultat = 0.0 ;
                    entree = "" ;
                    operateur = "";

                    jL_operateur.setText("");
                    jL_entree.setText("Erreur");
                }
            }

            
        }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        entree = entree.substring(0, entree.length() - 1);
        jL_entree.setText(entree);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(entree.length() < 7){
            entree = entree+"1";
            jL_entree.setText(entree);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(entree.length() < 7){
            entree = entree+"2";
            jL_entree.setText(entree);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(entree.length() < 7){
            entree = entree+"3";
            jL_entree.setText(entree);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(entree.length() < 7){
            entree = entree+"4";
            jL_entree.setText(entree);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if(entree.length() < 7){
            entree = entree+"5";
            jL_entree.setText(entree);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if(entree.length() < 7){
            entree = entree+"6";
            jL_entree.setText(entree);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if(entree.length() < 7){
            entree = entree+"7";
            jL_entree.setText(entree);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        if(entree.length() < 7){
            entree = entree+"8";
            jL_entree.setText(entree);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        if(entree.length() < 7){
            entree = entree+"9";
            jL_entree.setText(entree);
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        if(entree.length() < 7){
            entree = entree+"0";
            jL_entree.setText(entree);
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        if(entree.length() == 0){
            entree = entree+"+";
            jL_entree.setText(entree);
        }
        else{
            
            if(operateur.length() == 0){

                try{
                    
                    operande1 = Double.parseDouble(entree.replace(",", "."));
                    operateur = "+" ;
                    jL_operateur.setText(operateur);
                    entree = "";
                    jL_entree.setText(entree);
                }
                catch(Exception e){
                    operande1 = 0.0 ;
                    operande2 = 0.0 ;
                    resultat = 0.0 ;
                    entree = "" ;
                    operateur = "";

                    jL_operateur.setText("");
                    jL_entree.setText("Erreur");
                }
            }
            
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        if(entree.length() == 0){
            entree = entree+"-";
            jL_entree.setText(entree);
        }
        else{
            
            if(operateur.length() == 0){

                try{
                    operande1 = Double.parseDouble(entree.replace(",", "."));
                    operateur = "-" ;
                    jL_operateur.setText(operateur);
                    entree = "";
                    jL_entree.setText(entree);
                }
                catch(Exception e){
                    operande1 = 0.0 ;
                    operande2 = 0.0 ;
                    resultat = 0.0 ;
                    entree = "" ;
                    operateur = "";

                    jL_operateur.setText("");
                    jL_entree.setText("Erreur");
                }
            }
            
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        try{
            Double.parseDouble(entree);
            
            if(! entree.contains(".")){
                entree = entree + ".";
                jL_entree.setText(entree);
            }
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        if(entree.length() != 0){
            
            if(operateur.length() == 0){
                try{
                    operande1 = Double.parseDouble(entree.replace(",", "."));

                    operateur = "*" ;
                    jL_operateur.setText(operateur);

                    entree = "";
                    jL_entree.setText(entree);
                }
                catch(Exception e){
                    operande1 = 0.0 ;
                    operande2 = 0.0 ;
                    resultat = 0.0 ;
                    entree = "" ;
                    operateur = "";

                    jL_operateur.setText("");
                    jL_entree.setText("Erreur");
                }
            }

            
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
 
        
        if((entree.length() != 0) && (operateur.length() != 0)){
            
            
                try{
                    operande2 = Double.parseDouble(entree);

                    if(operateur.equals("+")){
                        entree = "";
                        entree = String.format("%.3f", (operande1 + operande2)) ;
                        operateur = "";
                        jL_operateur.setText(operateur);
                        jL_entree.setText(entree);
                    }
                    
                    if(operateur.equals("-")){
                        entree = "";
                        entree = String.format("%.3f", (operande1 - operande2)) ;
                        operateur = "";
                        jL_operateur.setText(operateur);
                        jL_entree.setText(entree);
                    }
                    
                    if(operateur.equals("*")){
                        entree = "";
                        entree = String.format("%.3f", (operande1 * operande2)) ;
                        operateur = "";
                        jL_operateur.setText(operateur);
                        jL_entree.setText(entree);
                    }
                    
                    if(operateur.equals("/")){
                        
                        if(operande2 == 0){
                            operande1 = 0.0 ;
                            operande2 = 0.0 ;
                            resultat = 0.0 ;
                            entree = "" ;
                            operateur = "";
                            
                            operateur = "";
                            jL_operateur.setText(operateur);

                            jL_entree.setText("Erreur");
                        }
                        else{
                            entree = "";
                            entree = String.format("%.3f", (operande1 / operande2)) ;
                            operateur = "";
                            jL_operateur.setText(operateur);
                            jL_entree.setText(entree);
                        }
                    }
                    
                }
                catch(Exception e){
                    operande1 = 0.0 ;
                    operande2 = 0.0 ;
                    resultat = 0.0 ;
                    entree = "" ;
                    operateur = "";

                    jL_operateur.setText("");
                    jL_entree.setText("Erreur");
                }
            

            
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        operande1 = 0.0 ;
        operande2 = 0.0 ;
        resultat = 0.0 ;
        entree = "" ;
        operateur = "";

        jL_operateur.setText("");
        jL_entree.setText("");
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Impression facture 
        
        String cl = jT_fidelite.getText() ;
        String titre ;
        Vente v ;
        
        //type facture.getValueAt(i, 3)
        
        for(int i=0 ; i < facture.getRowCount() ; i++){
            v = new Vente(facture.getValueAt(i, 0).toString() + "_" + Miniprojetjava.baseDeDonnees.getIdType(facture.getValueAt(i, 3).toString())  + "_" + id_client + "_" + id_pointvente + "_" + le_caissier.idcaissier + "_" + facture.getValueAt(i, 2).toString() + "_" + date + "_0"  );
            Miniprojetjava.baseDeDonnees.ajouterVente_BD(v);
            Miniprojetjava.baseDeDonnees.miseajourquantitestock(v.idproduit, v.quatite);
        }
        
        
        if(cl.equals("")){
            titre = "- "+ jL_pointvente.getText() + " - "+jL_total.getText() ;
        }
        else{
            titre = "- "+ jL_pointvente.getText() + " - "+cl+", "+jL_total.getText()  ;
        }
        
        MessageFormat entete = new MessageFormat(titre);
        
        try {
            facture.print(JTable.PrintMode.FIT_WIDTH, entete, null);
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, "Erreur : \n" + e, "Impression", JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(null, "Bonjour, bienvenue sur mon application.", "Message d'information", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        
        int option = JOptionPane.showOptionDialog(
                    null,                             // Parent component
                    "Voulez-vous vraiment fermer cette page ?",       // Message
                    "Confirmation",                  // Titre de la boîte de dialogue
                    JOptionPane.YES_NO_OPTION,        // Type de boîte de dialogue
                    JOptionPane.QUESTION_MESSAGE,    // Type d'icône
                    null,                             // Options personnalisées
                    null,                             // Option sélectionnée par défaut
                    null                              // Options de fermeture de la boîte de dialogue
                );

        if (option == JOptionPane.YES_OPTION) {

            Home.jPanel_main.setLayout(new BorderLayout());
            Home.jPanel_main.removeAll();
            JPanel_Home jp_home = new JPanel_Home();
            Home.jPanel_main.add(jp_home);
            Home.jPanel_main.revalidate();

        }
        
    }//GEN-LAST:event_jLabel16MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boutonmisejour;
    private javax.swing.JButton boutonAjouter;
    private javax.swing.JButton boutonSupp;
    private javax.swing.JTable facture;
    private javax.swing.JLabel inforechercheclient;
    private javax.swing.JLabel inforechercheproduit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jC_type;
    private javax.swing.JLabel jL_date;
    private javax.swing.JLabel jL_entree;
    private javax.swing.JLabel jL_nomCaissier;
    private javax.swing.JLabel jL_operateur;
    private javax.swing.JLabel jL_pointvente;
    private javax.swing.JLabel jL_total;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jT_fidelite;
    private javax.swing.JTextField jT_id_produit;
    private javax.swing.JTextField jT_prix;
    private javax.swing.JTextField jT_produit;
    private javax.swing.JTextField jT_qtitepoids;
    private javax.swing.JTextField jT_remise;
    private javax.swing.JLabel message;
    private javax.swing.JTextField nomproduit;
    private javax.swing.JLabel prix;
    private javax.swing.JTextField rechercheclient;
    private javax.swing.JTable resultatRechercheClient;
    private javax.swing.JTable resultatRecherchePdt;
    // End of variables declaration//GEN-END:variables
}
